<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:ns1="http://schemas.android.com/tools" xmlns:ns2="urn:oasis:names:tc:xliff:document:1.2">
    <attr format="reference" name="appBarLayoutStyle"/>
    <attr format="reference" name="badgeStyle"/>
    <attr format="reference" name="bottomAppBarStyle"/>
    <attr format="reference" name="bottomNavigationStyle"/>
    <attr format="reference" name="bottomSheetDialogTheme"/>
    <attr format="reference" name="bottomSheetStyle"/>
    <attr format="reference" name="checkedIcon"/>
    <attr format="color" name="checkedIconTint"/>
    <attr format="reference" name="chipGroupStyle"/>
    <attr format="reference" name="chipStandaloneStyle"/>
    <attr format="reference" name="chipStyle"/>
    <attr format="reference" name="circularProgressIndicatorStyle"/>
    <attr format="reference" name="clockIcon"/>
    <attr format="reference" name="collapsingToolbarLayoutLargeSize"/>
    <attr format="reference" name="collapsingToolbarLayoutLargeStyle"/>
    <attr format="reference" name="collapsingToolbarLayoutMediumSize"/>
    <attr format="reference" name="collapsingToolbarLayoutMediumStyle"/>
    <attr format="reference" name="collapsingToolbarLayoutStyle"/>
    <attr format="color" name="colorContainer"/>
    <attr format="color" name="colorErrorContainer"/>
    <attr name="colorOnBackground"/>
    <attr format="color" name="colorOnContainer"/>
    <attr format="color" name="colorOnError"/>
    <attr format="color" name="colorOnErrorContainer"/>
    <attr format="color" name="colorOnPrimary"/>
    <attr format="color" name="colorOnPrimaryContainer"/>
    <attr format="color" name="colorOnPrimarySurface"/>
    <attr format="color" name="colorOnSecondary"/>
    <attr format="color" name="colorOnSecondaryContainer"/>
    <attr format="color" name="colorOnSurface"/>
    <attr format="color" name="colorOnSurfaceInverse"/>
    <attr format="color" name="colorOnSurfaceVariant"/>
    <attr format="color" name="colorOnTertiary"/>
    <attr format="color" name="colorOnTertiaryContainer"/>
    <attr format="color" name="colorOutline"/>
    <attr format="color" name="colorPrimaryContainer"/>
    <attr format="color" name="colorPrimaryInverse"/>
    <attr format="color" name="colorPrimarySurface"/>
    <attr format="color" name="colorPrimaryVariant"/>
    <attr format="color" name="colorSecondary"/>
    <attr format="color" name="colorSecondaryContainer"/>
    <attr format="color" name="colorSecondaryVariant"/>
    <attr format="color" name="colorSurface"/>
    <attr format="color" name="colorSurfaceInverse"/>
    <attr format="color" name="colorSurfaceVariant"/>
    <attr format="color" name="colorTertiary"/>
    <attr format="color" name="colorTertiaryContainer"/>
    <attr format="dimension" name="dividerInsetEnd"/>
    <attr format="dimension" name="dividerInsetStart"/>
    <attr format="reference" name="dynamicColorThemeOverlay"/>
    <attr format="color" name="elevationOverlayAccentColor"/>
    <attr format="color" name="elevationOverlayColor"/>
    <attr format="boolean" name="elevationOverlayEnabled"/>
    <attr format="boolean" name="enableEdgeToEdge"/>
    <attr format="boolean" name="ensureMinTouchTargetSize"/>
    <attr format="reference" name="extendedFloatingActionButtonPrimaryStyle"/>
    <attr format="reference" name="extendedFloatingActionButtonSecondaryStyle"/>
    <attr format="reference" name="extendedFloatingActionButtonStyle"/>
    <attr format="reference" name="extendedFloatingActionButtonSurfaceStyle"/>
    <attr format="reference" name="extendedFloatingActionButtonTertiaryStyle"/>
    <attr format="reference" name="floatingActionButtonLargePrimaryStyle"/>
    <attr format="reference" name="floatingActionButtonLargeSecondaryStyle"/>
    <attr format="reference" name="floatingActionButtonLargeStyle"/>
    <attr format="reference" name="floatingActionButtonLargeSurfaceStyle"/>
    <attr format="reference" name="floatingActionButtonLargeTertiaryStyle"/>
    <attr format="reference" name="floatingActionButtonPrimaryStyle"/>
    <attr format="reference" name="floatingActionButtonSecondaryStyle"/>
    <attr format="reference" name="floatingActionButtonStyle"/>
    <attr format="reference" name="floatingActionButtonSurfaceStyle"/>
    <attr format="reference" name="floatingActionButtonTertiaryStyle"/>
    <attr format="reference" name="headerLayout"/>
    <attr format="reference" name="hideMotionSpec"/>
    <attr format="boolean" name="isMaterial3Theme"/>
    <attr format="boolean" name="isMaterialTheme"/>
    <attr format="reference" name="itemShapeAppearance"/>
    <attr format="reference" name="itemShapeAppearanceOverlay"/>
    <attr format="color" name="itemTextColor"/>
    <attr format="reference" name="keyboardIcon"/>
    <attr format="reference" name="linearProgressIndicatorStyle"/>
    <attr format="reference" name="materialButtonOutlinedStyle"/>
    <attr format="reference" name="materialButtonStyle"/>
    <attr format="reference" name="materialButtonToggleGroupStyle"/>
    <attr format="reference" name="materialCalendarDay"/>
    <attr format="reference" name="materialCalendarDayOfWeekLabel"/>
    <attr format="reference" name="materialCalendarFullscreenTheme"/>
    <attr format="reference" name="materialCalendarHeaderCancelButton"/>
    <attr format="reference" name="materialCalendarHeaderConfirmButton"/>
    <attr format="reference" name="materialCalendarHeaderDivider"/>
    <attr format="reference" name="materialCalendarHeaderLayout"/>
    <attr format="reference" name="materialCalendarHeaderSelection"/>
    <attr format="reference" name="materialCalendarHeaderTitle"/>
    <attr format="reference" name="materialCalendarHeaderToggleButton"/>
    <attr format="reference" name="materialCalendarMonth"/>
    